### ISSUE TITLE
Unable to install on python3.7 environment

### ISSUE THREAD

**Issue by danielpops** [aws/aws-msk-iam-sasl-signer-python#20]
* aws-msk-iam-sasl-signer-python version: 1
* Python version: 3.7
* Operating System: ubuntu
* Method of installation: pip/poetry
* Kafka library name: both `kafka-python` and `confluent-kafka`
* Kafka library version: unsure

### Description

Cannot install on python3.7 environment. The latest versions of `kafka-python` and `confluent-kafka` support lower python versions than 3.8 so ideally this library would be a little less restrictive on the versions of python it supports.

### What I Did

```
$ python --version
Python 3.7.13
$ pip install aws-msk-iam-sasl-signer-python==1.0.0
ERROR: Ignored the following versions that require a different python version: 1.0.0 Requires-Python >=3.8
ERROR: Could not find a version that satisfies the requirement aws-msk-iam-sasl-signer-python==1.0.0
ERROR: No matching distribution found for aws-msk-iam-sasl-signer-python==1.0.0
```

**Comment by sankalpbhatia** [comment]
Thanks for raising this. We'll get back to you soon after discussing internally.

**Comment by sankalpbhatia** [comment]
Hi @danielpops, Apologies for the delay on this. I am afraid we do not plan to support this library for Python versions less than 3.8 as those have crossed their EOL dates.
