### ISSUE TITLE
Dependency versions (boto3, botocore)

### ISSUE THREAD

**Issue by mlacroix-ipsos** [aws/aws-msk-iam-sasl-signer-python#21]
* aws-msk-iam-sasl-signer-python version: 1.0.0
* Python version: 3.10.11
* Operating System: Linux (Ubuntu)
* Method of installation: pip
* Kafka library name: kafka-python
* Kafka library version: 2.0.2
* Provide us a sample code snippet of your producer/consumer

### Description

The dependencies of boto3 and botocore are pinned at versions from several months ago and are missing newer functionality (e.g. S3 Express One Zone support). Is there a plan for these to be upgraded periodically?

**Comment by lucasmo** [comment]
These appear to be pinned in https://github.com/aws/aws-msk-iam-sasl-signer-python/blob/main/setup.py#L18

**Comment by sankalpbhatia** [comment]
This seems like a miss. @mlacroix-ipsos Would you be willing to open a PR for this?

**Comment by mlacroix-ipsos** [comment]
I don't mind putting a PR together, but what is the guidance for handling dependency version here? Do you want it pinned? And if so, do you want it as a specific version or some level of major/minor?

**Comment by sankalpbhatia** [comment]
It shouldn't be pinned. We can have `"boto3>=1.26.125", "botocore>=1.29.125"`

**Comment by sankalpbhatia** [comment]
Will pick up in next release
